# Generated by Django 4.2.15 on 2024-09-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=False)),
                ('updated_time', models.DateField(auto_now=True)),
                ('created_time', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'پست  ',
                'verbose_name_plural': 'پست ها ',
                'ordering': ['created_time'],
            },
        ),
    ]
