# Generated by Django 4.2.15 on 2024-10-10 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_post_tags_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_time']},
        ),
    ]
